### ISSUE TITLE
binding UI and MutableProperty

### ISSUE THREAD

**Issue by ajjnix** [ReactiveCocoa/ReactiveCocoa#2775] opened 2016-03-31 08:11 UTC
I have next code
`DynamicProperty(object: self.usernameLabel, keyPath: "text").producer <~ self.viewModel.username.producer
`

but I get error:
`Binary operator '<~' cannot be applied to operands of type 'SignalProducer<AnyObject?, NoError>' (aka 'SignalProducer<Optional<AnyObject>, NoError>') and 'SignalProducer<String, NoError>'
`

But it work if I write like
```DynamicProperty(object: self.usernameLabel, keyPath: "text") <~ self.viewModel.username.producer.map { $0 }```

what's different?
self.viewModel.username.producer is type SignalProducer<String, NoError>
self.viewModel.username.producer.map { $0 } is type SignalProducer<String, NoError>

Or I wrong?
And maybe have more pretty binding UI with property? I found solved https://github.com/brewfactory/BrewMobile/blob/master/BrewMobile/RACUtils/RAC.swift but write extension for each property UI not want

**Comment by iv-mexx** [comment] 2016-03-31 12:19
The problem is that DynamicProperty expects a `SignalProducer<AnyObject?>` and your `viewModel.username` is most likely something more specific, so your SignalProducer is not just of type `SignalProducer`, but `SignalProducer<T>`. 
As of right now, Swifts type inference is sometimes not able to correctly infer that `SignalProducer<T>` is a subtype of `SignalProducer<AnyObject?`, but with `.map { $0 }` the type inference gets it. 

See also #2719 

For more pretty UI bindings have a look at [Rex](https://github.com/neilpa/Rex)

**Comment by RuiAAPeres** [comment] 2016-04-14 13:32
@ajjnix if @iv-mexx answered your question, please close the issue. Otherwise, let us know how can we further assist you.

**Closed** 2016-04-14 14:09 UTC
Labels: question
