### ISSUE TITLE
MutableProperty initialise with SignalProducer

### ISSUE THREAD

**Issue by almassapargali** [ReactiveCocoa/ReactiveCocoa#2183] opened 2015-07-18 13:11 UTC
I often find myself in need of some `MutableProperty` (a) with mapped value of another `MutableProperty` (b). What I usually do is create some mapping function `t` with type of `(T) -> U`, then initialise a like `a = MutableProperty(t(b))` followed by `a <~ b |> map(t)`. Of course, I could initialise a with some dumb data since it gets replaced with initial value of another property's producer, or skip first value of that producer.

~~But, I think it'd be nice to have a constructor for `MutableProperty<T>` which takes `SignalProducer<T, NoError>` set's initial value of from producer, then observe changes to~~

What if `MutableProperty` had a constructor `initial: T, changes: Signal<T, NoError>`? And given #2146 is implemented it would be possible to use:
```
a = MutableProperty(b.value, b.signal |> map(t))
```

**Comment by jspahrsummers** [comment] 2015-07-18 15:09
Dupe of https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2006.

**Closed by jspahrsummers** 2015-07-18 15:09 UTC
