### ISSUE TITLE
Visual Identity Refresh for 4.0

### ISSUE THREAD

**Issue by kaishin** [ReactiveCocoa/ReactiveCocoa#2190] opened 2015-07-19 11:55 UTC
I've been meaning to open this issue for a while, but kept finding excuses, mainly the fact that 3.0 was far from release. That is no longer the case now.

Basically, I'd like to spearhead an effort to revamp the visual identity of RC and hopefully be done with that in time with the 3.0 final release.

For reference, here is the current logo/color palette:
<img width="349" alt="screenshot-2015-07-19-1" src="https://cloud.githubusercontent.com/assets/519433/8765769/50f98538-2e15-11e5-869d-ea7596c938b8.png">

I've played with the concept below a while ago, but I restarted from scratch recently after having talked to @jspahrsummers during WWDC.

<img width="430" alt="screenshot-11-14-1" src="https://cloud.githubusercontent.com/assets/519433/8765763/26e76f76-2e15-11e5-9581-2fbeb32fb23b.png">

Here are some of the recent sketches to get the creative juices flowing:

<img width="581" alt="screenshot-2015-07-19" src="https://cloud.githubusercontent.com/assets/519433/8765767/385c380e-2e15-11e5-93ad-ad385162097b.png">

I'll be detailing the rest of the process in this thread.

**Comment by jspahrsummers** [comment] 2015-07-20 01:35
I don't have much concrete feedback other than to say that I like the direction. :sparkles:

I'd like to avoid the atomic/nuclear stuff, though, given the existing designs for Atom, Electron, React, etc.

/cc @ReactiveCocoa/reactivecocoa

**Comment by rpowelll** [comment] 2015-07-20 01:45
I like the general colour scheme / type treatment in that logo mockup, but I think it'd make sense for the logo mark itself to incorporate the idea of changing values over time, railroad diagrams, or something that more explicitly communicates what the framework does.

**Comment by brow** [comment] 2015-07-20 03:39
Cool! Just so's you know, ReactiveCocoa is conventionally abbreviated "RAC" rather than "RC", for some reason. It might be confusing to deviate from that now.

**Comment by rpowelll** [comment] 2015-07-20 03:43
Yeah the RAC thing originates from Apple's recommendation that frameworks in Objective-C make use of a three letter prefix for namespacing. At this point it's been adopted as a general abbreviation for ReactiveCocoa, so we should probably stick with that.

**Comment by robrix** [comment] 2015-07-20 15:00
@kaishin:

1. I love your work :heart:
2. I _really_ dig the parallelogram/triangles + logotype version you give above the sketches. It’s abstract enough to accommodate the changes to the framework over the years, and I particularly like spelling ReactiveCocoa out in full.

I think values changing over time is perhaps too abstract a concept to communicate in a logo, so I’m personally :+1: on it as-is. That said, if you want to take a crack at it, don’t let me stop you!

**Comment by kaishin** [comment] 2015-07-20 16:47
Thank you everyone for the feedback.

I see potential in the original redesign concept, but I wanted to process to be open as well. We might end up there or somewhere close, but at least we would have explored some other directions for future reference.

Next step consists in taking some concepts from those sketches and rendering them to see if they are promising or not.

---

Thanks @robrix! I'm equally a big fan of your open-source work.

@rpowelll @brow Absolutely. My thinking was to try something new, but at the end of the day, I doubt RC or RAC will affect the final design in any noticeable way. I did use the spelled out RAC in this quick and dirt logo for a local event http://www.meetup.com/RAC-Night/ but I'd rather stay away from that.

@jspahrsummers https://twitter.com/kaishin/status/562696751371808769 ;)

**Comment by robrix** [comment] 2015-07-20 18:37
:bow:

**Comment by kastiglione** [comment] 2015-07-20 19:03
@kaishin Awesome of you to tackle this :green_heart:

**Comment by rpowelll** [comment] 2015-07-20 22:24
@kaishin awesome! Can't wait to see some of those concepts made more 'real', I'm a big fan of what's there already.

**Comment by kaishin** [comment] 2015-08-06 17:25
I've made some progress on the mark and would like to share it with everyone.

**Goals of this step**
Iterate on the logo mark and narrow down it's overall shape and composition. The mark will be used in icons, social media, swag, etc, and as such needs to be identifiable on its own. Colors in this step are only used to give an idea of how things might look.

**Process**
I did two separate iteration sprints, one starting from the mock I made a while a back, and one from the new triangle-based shape that I recently sketched (see above).

 :warning: Potential design highfalutin ahead :warning: 

Iterations 1, 2, and 3 are all slight variations on the original concept. While they are the simplest, they feel a bit vague without the logotype. Their sharpness is slightly menacing as well, and that's something to be aware of if the goal of RAC 3.0 is to simplify the API and make it more accessible to newcomers.

To address these issues, 4 and 5 introduce circular and linear shapes inspired from marble diagrams. Even though circles draw attention away from the sharp angles in 4, I tried round corner in 5 and wasn't displeased with the result. Iteration 5 looks more accurate as far as marble diagrams are concerned. It also looks similar to a chemical representation, and...a razor blade. Alas, both iterations feel "boxed", resulting in an unexciting look overall.

Iteration 6 was a lousy attempt to play with the circle in order to get something remotely resembling an uppercase R and a lowercase C.

Iterations 7, 8, and 9 are attempts to capture the notion of "change over time" through using marbles of varying sizes (that said, all three still need some size tweaks to reduce the empty areas).

Iteration 10 is made of two triangles, instead of one parallelogram.  Iteration 11 adds rounded corners on the outside. Both are too simplistic to be considered. Iteration 12 (latest) is an attempt to apply the marble diagram concept to 11.

![screenshot-2015-08-06](https://cloud.githubusercontent.com/assets/519433/9117390/bc5f794a-3c61-11e5-8f2d-7574a2915bf2.jpg)

**Next steps**
- Do a few more iterations based on 12, mainly to reduce visual clutter and streamline the overall shape.
- Iterate on colors
- Iterate on the logotype

**Comment by kastiglione** [comment] 2015-08-08 01:27
In case you're curious, I jumped right to the images and I found that I really liked number 6 the month (in color form). I'll read the update, but thought you might like to know that without context I was really drawn to 6.

**Comment by robrix** [comment] 2015-08-08 15:16
For me, 1, 3, and 11. Thanks so much for sharing your process @kaishin, it’s really neat seeing how you’ve developed this!

**Comment by jspahrsummers** [comment] 2015-08-08 17:32
I quite like the perspective involved in 8 and 9, but also like the split triangles in 11.

IMO the incorporation of marble diagrams is amazing, and I'd love to see some callout in whatever the final design ends up being.

@kaishin Great work! :star2::sparkles::zap:

**Comment by kaishin** [comment] 2015-08-14 00:50
Another iteration focusing on the mark.

To keep it short, the marbles proved to be trickier than I hoped. They add a level of details that makes the mark overly complex. I did few extra takes to incorporate them, but none of them looked good. (6) is the closest to an acceptable level of detail, but even then the narrow gap between the triangles won't be visible in small sizes.

As such I decided to backpedal and try without, resulting in (3), (4), and (5). These ended up being my favorites in terms of simplicity, abstractness level, and visual balance. (5) preserves the "R" shape the most, whereas (4) makes the two triangles more identifiable and will allow some interesting color combinations.

![take 3](https://cloud.githubusercontent.com/assets/519433/9265094/39fe1130-4226-11e5-8b7f-9c09bd523e93.jpg)

Here are some potential renditions to make it easier for everyone to see how these might end up looking:
![take 3 alts type](https://cloud.githubusercontent.com/assets/519433/9265108/81c807dc-4226-11e5-9c5a-ed2b606e92d9.jpg)

I'd be interested to hear everyone's preferences.

**Next steps**
- Iterate on colors
- Iterate on the logotype

**Comment by rpowelll** [comment] 2015-08-14 02:43
I definitely like the top right one quite a lot

**Comment by tobiasahlin** [comment] 2015-08-14 08:16
@kaishin :clap::clap::clap: Great work on this.

I love the bottom left one. (It could be interesting to play around with letting the two shapes bend into each other, like to sheets of paper. Quick mock :point_down:)

<img width="1011" alt="screen shot 2015-08-14 at 10 15 06" src="https://cloud.githubusercontent.com/assets/211284/9269840/5e42d944-426d-11e5-905d-4377ce4dec21.png">

**Comment by robb** [comment] 2015-08-14 08:21
@tobiasahlin I really dig that wraparound look :heart_eyes:

**Comment by kaishin** [comment] 2015-08-14 09:10
@tobiasahlin :100: That was definitely on my radar, especially after playing around a bit with colors and noticing that there could be something to do with a paper folding effect. The lower left mocks were last minute additions to try to tone done details even more.

**Comment by JaviSoto** [comment] 2015-08-14 17:08
I love it! I also prefer the simpler version with just 2 tones of green.

**Comment by neilpa** [comment] 2015-08-14 22:03
Piling on the look for the simpler folded paper look

**Comment by NachoSoto** [comment] 2015-08-14 22:18
It's been amazing to see the progress. I agree with the rest: the folded paper look is gorgeous :clap:

**Comment by kaishin** [comment] 2015-08-14 22:51
Building up on @tobiasahlin's suggestion and other feedback, here are some color renditions, including a couple of gradient-based ones.

<img width="509" alt="screenshot-2015-08-14" src="https://cloud.githubusercontent.com/assets/519433/9285571/0e2c61ba-42df-11e5-8f53-97670b05dc8d.png">

**Comment by rpowelll** [comment] 2015-08-17 03:37
I really like number 3 and 4

**Comment by ScottRobbins** [comment] 2015-08-19 07:11
I like number 4 the best.

**Comment by robb** [comment] 2015-08-19 07:24
I'd go with number 4 with a fallback to 3 wherever the gradient is hard to reproduce (t-shirts, tattoos, zeppelin decals…)

**Comment by MarcoSero** [comment] 2015-08-19 08:05
Agree with @robb. I find n. 4 really beautiful but 3 is good too whenever using 4 is not possible.

**Comment by kaishin** [comment] 2015-08-19 08:20
Exactly my thought when I made these. (4) for large digital representations and (3) for print, small icons, etc.

That said we still need a purely monochrome version which I will work on shortly.

**Comment by tobiasahlin** [comment] 2015-08-19 11:41
:heart: Love no. 4 as well, great work @kaishin :bow:

**Comment by tonyarnold** [comment] 2015-08-20 23:48
This looks amazing. Can't wait to see things like the documentation inspired by these colours and ideas. Great work!

**Comment by nomothetis** [comment] 2015-08-21 18:51
Late to the party, but this looks great. :100:

**Comment by TerryHug2305** [comment] 2015-08-21 23:27
excellent! I like 4 and 5

**Comment by kaishin** [comment] 2015-09-06 18:30
Added color values and monochrome versions.

<img width="456" alt="screenshot-2015-09-06" src="https://cloud.githubusercontent.com/assets/519433/9705947/f8f6e276-54d5-11e5-8312-916b884cd65c.png">

**Comment by neilpa** [comment] 2015-09-06 18:54
:100: :clap:

**Comment by bencochran** [comment] 2015-09-13 22:04
This looks beautiful. Nice work! (And fun to read back over the progress)

One *tiny* thing that’s catching my eye: the “c” in “Reactive” feels like it could be kerned a little to the left.

**Comment by neilpa** [comment] 2015-09-13 22:05
> the “c” in “Reactive” feels like it could be kerned a little to the left.

Now that you mention it...

**Comment by kaishin** [comment] 2015-09-14 08:09
Good catch @bencochran. Will do another pass.

**Comment by okla** [comment] 2015-09-17 10:37
Nice icon! Reminds [Replay](https://itunes.apple.com/us/app/replay-video-editor-make-movie/id694164275?mt=8)

**Comment by kaishin** [comment] 2015-09-19 22:22
@okla I'm seeing this for the first time :persevere: Our process is public so I am not worried about accusations of copying it... or should I be? At any rate, I don't expect any simple-looking logo mark to be truly unique nowadays.

**Comment by jspahrsummers** [comment] 2015-10-02 09:19
Looks great! Perfect for appropriating into the @facebook org!!!!1

![](http://media.giphy.com/media/p7RpYa0hiK7q8/giphy.gif)

**Comment by neilpa** [comment] 2015-10-22 19:51
Moving to 4.0 since the 3.0 ship has sailed.

**Comment by kaishin** [comment] 2015-10-23 09:33
Thanks @neilpa. I think this should be wrapped up. I'll open a PR with assets.

**Comment by NachoSoto** [comment] 2015-10-23 16:53
😍

**Comment by neilpa** [comment] 2015-11-26 19:12
Resolved by #2574

**Closed by neilpa** 2015-11-26 19:12 UTC
Labels: enhancement
