### ISSUE TITLE
Swift 2: `start` with trailing closure does not default to `next`

### ISSUE THREAD

**Issue by Adlai-Holler** [ReactiveCocoa/ReactiveCocoa#2294] opened 2015-08-27 18:02 UTC
This may be intentional, but on the Swift 2 branch if I call `myProducer.start { NSLog("\($0)") }` I get events, rather than next values.

**Comment by neilpa** [comment] 2015-08-27 18:24
I'm going to blame the compiler on this one. There's not enough context to know that you want the `next` variant here so it picks the single-arg overload.

Personally, I was never a fan of the change that made `next` be the trailing closure for this exact reason. I even broke it in one of the earlier betas by reordering the params but later reverted it.

**Comment by swizzlr** [comment] 2015-08-30 18:44
I've encountered this too, but you can still get the trailing closure syntax by explicitly specifying the type of the parameter, or by using it in a type specific context (e.g. if `next` is a String, assigning it to a property of type String, most of the time the compiler will infer the type and overload correctly)

**Comment by ikesyo** [comment] 2016-04-23 12:11
Closing as a duplicate of #2311 (resolved by #2318).

**Closed by ikesyo** 2016-04-23 12:11 UTC
Labels: duplicate
