### ISSUE TITLE
Crash issue when dealloc object (maybe related with RACObserve)

### ISSUE THREAD

**Issue by luohui8891** [ReactiveCocoa/ReactiveCocoa#2656] opened 2016-01-12 07:13 UTC
Hi guys,
Thank you for the awesome tool which made the code easier.
We used ReactiveCocoa 2.4.4 in our project like following
```
[RACObserve(sharedModel, profile.avatar) subscribeNext:^(id x) {
    // do something
}];
```
The `sharedModel` is a singleton instance of ClassA.
The `profile` a property of shareModel is an instance of ClassB. 
The `avatar` is instance of NSString.

We would set "profile" to another new instance when new profile data loaded. Code like this:
```
sharedModel.profile = [TKProfile profileWithDict:profileHash];
```
We got some crash reported from users which I can't reproduce it in my side.  The reason is 
```
An instance 0x14d686680 of class TKProfile was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x14eb8c8d0> (
<NSKeyValueObservance 0x14eb8c8a0: Observer: 0x14d72c540, Key path: avatar, Options: <New: NO, Old: NO, Prior: YES> Context: 0x14eb8c650, Property: 0x14d6c9950>
)
```

I have reviewed some source code of ReactiveCocoa and noticed that the object which add observer by `RACObserve` would be remove all observer when property changed. In this case, both `sharedModel` and `profile` would be toke care by ReactiveCocoa, right?
Do you guys have any idea about this crash issue?

**Comment by ikesyo** [comment] 2016-05-06 09:48
This is a duplicate of #1122 and #2308. `RACKVOTrampoline` was re-implemented in #1627 and this should be fixed from the v2.4.6 release. Closing.

**Closed by ikesyo** 2016-05-06 09:48 UTC
Labels: bug, duplicate, legacy-objc
