### ISSUE TITLE
xcode 9 ReactiveCocoa error 

### ISSUE THREAD

**Issue by xiaoruiling** [ReactiveCocoa/ReactiveCocoa#3538] opened 2017-11-13 11:00 UTC
**## I used xcode 9.0 + cocopods
pod install success**
![image](https://user-images.githubusercontent.com/8361817/32722256-f64539e6-c82e-11e7-9b52-06b9599a3268.png)

**## But ,There are a lot of errors to run** 
![image](https://user-images.githubusercontent.com/8361817/32722365-4da2aad4-c82f-11e7-8012-de9e3da5100d.png)

help ?

**Comment by ikesyo** [comment] 2017-11-13 11:09
This is a duplicate of #3525.

**Closed by ikesyo** 2017-11-13 11:09 UTC
