### ISSUE TITLE
Error with ReactiveCocoa and AFNetworking

### ISSUE THREAD

**Issue by bhowell2** [ReactiveCocoa/ReactiveCocoa#2257] opened 2015-08-13 05:38 UTC
I've got AFNetworking and ReactiveCocoa manually imported into my project. I'm getting a strange error when combining the two in this manner:

```Swift
typealias DownloadResponse = (response: NSURLResponse, imageUrl: NSURL)
    func downloadImageSignal(#route: String, destinationFolder: NSURL) -> SignalProducer<DownloadResponse, NSError> {
        //var progressWatcher: NSProgress? = NSProgress()
        var req = NSURLRequest(URL: NSURL(string: route, relativeToURL: self.baseURL)!)
    
        return SignalProducer {
            sink, disposable in
            self.downloadTaskWithRequest(req, progress: nil, destination: { (tmpUrl, urlResponse) -> NSURL! in
                if let suggestedFilename = urlResponse.suggestedFilename {
                    return destinationFolder.URLByAppendingPathComponent(suggestedFilename)
                } else {
                    sendError(sink, NSError(domain: "Server did not supply a file name", code: ErrorCodes.ServerDidNotSendImageName, userInfo: nil))
                }
                return tmpUrl
                }, completionHandler: { (urlResponse, savedUrl, error) -> Void in
                //
                sendNext(sink, (urlResponse, savedUrl))
                sendCompleted(sink)
            })
        }
        
    }
```

Does anyone have any idea what may be causing the error? (I don't know what the error actually is, as I get the informative `failed with exit code 1` message.)  Seems to be some issue with the way AFNetworking and ReactiveCocoa are interacting here? I don't have any other problems with AFNetworking and SignalProducers.

**Comment by ikesyo** [comment] 2015-08-13 06:33
This seems duplicate of #2106 and #2204.

**Closed by ikesyo** 2015-08-13 06:33 UTC
Labels: question

**Comment by bhowell2** [comment] 2015-08-13 12:19
thanks :+1:  didn't look around enough
