### ISSUE TITLE
ReactiveCocoa 4.2.1 doesn't compile with Xcode 7.3.1

### ISSUE THREAD

**Issue by anton-matosov** [ReactiveCocoa/ReactiveCocoa#3034] opened 2016-07-06 06:54 UTC
```
SignalProducer.swift
Error:(84, 23) ambiguous use of 'debounce(_:onScheduler:)'
```

```
public func debounce(interval: NSTimeInterval, onScheduler scheduler: DateSchedulerType) -> SignalProducer<Value, Error> {
        return lift { $0.debounce(interval, onScheduler: scheduler) }  <<<----
    }
```

**Comment by ikesyo** [comment] 2016-07-06 10:11
This is a duplicate of https://github.com/RACCommunity/Rex/issues/131. Could you please follow the Rex repo? Closing.

**Closed by ikesyo** 2016-07-06 10:11 UTC
