### ISSUE TITLE
SignalProducer and Swift not compiling

### ISSUE THREAD

**Issue by bjarkehs** [ReactiveCocoa/ReactiveCocoa#2204] opened 2015-07-22 09:36 UTC
Hi,

I've just been upgrading a work project to RAC3, but after finally getting around to removing all the old RAC2.5 from our Swift I ran into the issue that the compiler wouldn't compile the Swift files.

More specifically I got the error 
```bash
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

After removing most of the ReactiveCocoa code I finally found (at least) one of the issues causing it. I had a method:

```swift
func signalProducerForHomeWithOTP(otp: String) -> SignalProducer<Home, NSError> {
    return SignalProducer { [weak self] sink, disposable in
        self?.homeManager.addHomeWithOTP(otp, asTest: self!.test) { home, error in
            if let error = error {
                sendError(sink, error)
            } else if let home = home {
                sendNext(sink, home)
                sendCompleted(sink)
            }
        }
    }
}
```

That was causing the error. If I removed sendError, sendNext, and sendCompleted it would compile just fine. However, if I instead changed the method to this:

```swift
func signalProducerForHomeWithOTP(otp: String) -> SignalProducer<Home, NSError> {
    let otp = otp
    let homeManager = self.homeManager
    let asTest = self.test
    return SignalProducer { sink, disposable in
        homeManager.addHomeWithOTP(otp, asTest: asTest) { home, error in
            if let error = error {
                sendError(sink, error)
            } else if let home = home {
                sendNext(sink, home)
                sendCompleted(sink)
            }
        }
    }
}
```

Then everything works fine. Granted I am not a master of Swift, but I figured the first should work?

**Comment by bjarkehs** [comment] 2015-07-22 09:46
Further investigation seems to indicate that it has nothing to do with self but rather a method call on an optional.

```swift
func signalProducerForUpdateHomeName(name: String) -> SignalProducer<Void, NSError> {
    return SignalProducer { [weak self] sink, disposable in
        self?.home?.updateName(name) { (error) -> Void in
            if let error = error {
                sendError(sink, error)
            } else {
                sendNext(sink, ())
                sendCompleted(sink)
            }
        }
    }
}
```

The above method causes the Swift compiler to break, whereas the following works just fine:
```swift
func signalProducerForUpdateHomeName(name: String) -> SignalProducer<Void, NSError> {
    return SignalProducer { [weak self] sink, disposable in
        if let home = self?.home {
            home.updateName(name) { (error) -> Void in
                if let error = error {
                    sendError(sink, error)
                } else {
                    sendNext(sink, ())
                    sendCompleted(sink)
                }
            }
        }
    }
}
```

**Comment by ikesyo** [comment] 2015-07-22 09:57
Dupe of #2106.

**Closed by ikesyo** 2015-07-22 09:57 UTC

**Comment by bjarkehs** [comment] 2015-07-22 10:05
Thanks!
