### ISSUE TITLE
Xcode 7.3 beta 5 miscompiles `SignalProducerType.combineLatestWith` on ARM64

### ISSUE THREAD

**Issue by jckarter** [ReactiveCocoa/ReactiveCocoa#2751] opened 2016-03-04 21:18 UTC
I hate to incovenience you all, but we have a bug in the 7.3 betas that causes us to miscompile the currying of `Signal.combineLatestWith` here:

```swift
	public func combineLatestWith<U>(otherProducer: SignalProducer<U, Error>) -> SignalProducer<(Value, U), Error> {
		return liftRight(Signal.combineLatestWith)(otherProducer)
	}
```

I'm investigating a fix right now. In case we don't fix it in time for 7.3 final, I recommend hand-inlining the `liftRight` combinator here as a workaround, 

```swift
	public func combineLatestWith<U>(otherProducer: SignalProducer<U, Error>) -> SignalProducer<(Value, U), Error> {	
		return SignalProducer { observer, outerDisposable in
			self.startWithSignal { signal, disposable in
				outerDisposable.addDisposable(disposable)
					
				otherProducer.startWithSignal { otherSignal, otherDisposable in
					outerDisposable.addDisposable(otherDisposable)
						
					signal.combineLatestWith(otherSignal).observe(observer)
				}
			}
		}
	}
```

The bug on our side is rdar://problem/24960559, for reference.

**Comment by NachoSoto** [comment] 2016-03-04 21:25
I can't even begin to express how excited I am to see a Swift contributor open an issue, not only explaining the bug but offering a work around :heart_eyes: 

If it's not fixed by the GM we can temporarily make this change in #2684, since we'll likely need to change other things for `Swift 2.2`.

Thanks a lot @jckarter :smile:

**Comment by mdiep** [comment] 2016-03-05 02:16
> I can't even begin to express how excited I am to see a Swift contributor open an issue, not only explaining the bug but offering a workaround

Yes! Thank you!!! :heart_eyes:

**Comment by calebd** [comment] 2016-03-08 18:29
@jckarter Is there an issue on bugs.swift.org that we can follow as well?

**Comment by jckarter** [comment] 2016-03-08 21:07
Not that I know of. The radar unfortunately contains a private project I can't post publicly.

**Comment by NachoSoto** [comment] 2016-03-21 21:39
@calebd reports that this is still an issue on the final 7.3. I'm finishing the download now, and I'll make a branch with 2.2 changes (probably including this _hopefully_ temporary workaround) and try to make a release by EOD today.

**Comment by NachoSoto** [comment] 2016-03-21 23:22
Confirmed, this crashes when running tests with `-O`. I added a workaround in #2760: 6f63eb6569772a90f0b4358acb33b93a4f8105b2.

**Comment by mdiep** [comment] 2016-03-26 16:32
Fixed by #2760.

**Comment by NachoSoto** [comment] 2016-03-26 23:10
Let's keep this open so that we remember to get rid of the workaround once this is fixed in Swift :)

**Comment by calebd** [comment] 2016-03-28 16:48
@jckarter Any idea if this will be fixed in the [2.2.x milestone](https://github.com/apple/swift/milestones/Swift%202.2.x)?

**Comment by jckarter** [comment] 2016-03-28 19:29
We'll try, at least. We're looking into it.

**Comment by jckarter** [comment] 2016-03-29 00:38
Looks like @eeckstein has a fix on the way: https://github.com/apple/swift/pull/1916

**Comment by ikesyo** [comment] 2016-04-20 14:32
It seems that this is fixed by https://github.com/apple/swift/pull/1937 and Xcode 7.3.1 / Swift 2.2.1 contains the fix.

**Comment by mdiep** [comment] 2016-08-08 00:11
The workarounds have been removed for Swift 3!

**Closed by mdiep** 2016-08-08 00:11 UTC
Labels: bug
