### ISSUE TITLE
Is RAC4 viable in production apps, given its alpha status?

### ISSUE THREAD

**Issue by ceeK** [ReactiveCocoa/ReactiveCocoa#2697] opened 2016-01-30 22:33 UTC
I've just been reading up on ReactiveCocoa and I've become very excited about its use cases. It'd fix a perfect view controller bloat in a production app of mine, but I'm concerned of whether it's in a good enough state do rely on? 

A related question: when a new version of Swift comes out, how long are the turn around times for compatibility? 

Thanks

**Comment by mdiep** [comment] 2016-01-30 23:54
v4.0 was shipped this past week—it's no longer considered an alpha version. Some people have been using it in production apps for some time now.

Turnaround times on new Swift versions depend on how drastic the changes are and how available contributors are.

**Comment by NachoSoto** [comment] 2016-01-31 02:20
Turnaround times should be usually 1 day at most for stable versions. Can't promise that we'll have branches ready for each Swift beta, though.

**Comment by dfischbach** [comment] 2016-02-01 14:59
Thank you for your great work!
Are there any plans to reflect the changes for RAC4 in an updated documentation or something like a cheat sheet in the near future?
I'd like to use it for upcoming projects but getting the simplest binding to work is currently a pain. Nearly all search results are pointing to outdated examples for older RAC versions. With no experience in older RAC versions it costs a lot of time to dig in the source code to check if classes/operators are gone or if only the swift syntax is wrong. As an example I'm actually trying to setup a simple two-way binding with RACChannels and I'm always asking me if its really that complicated or did I miss something?
It would be really great to have a cheat sheet which shows the every day needed solutions for binding a view to a view model by showing command bindings with UI elements, one-way and two-way bindings.

**Comment by mdiep** [comment] 2016-02-01 15:00
Check out the [CHANGELOG](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/CHANGELOG.md).

**Comment by ILI4S** [comment] 2016-02-06 21:53
@ceeK I wouldn't consider a project with >200 open issues to be production-viable, especially when you see that project recently having made breaking API changes that invalidate prior documentation.

the changes doc that @mdiep is certainly _very_ helpful but raises more questions that it answers, at least in my reading.

(for an example of an extremely well-managed production-ready open source Swift project take a look at [Alamofire](https://github.com/Alamofire/Alamofire) -- it has 3 open issues and clear, accessible, and organized migration guides with detailed explanations for the API changes that were made.)

it is ultimately up to the developer integrating the dependency to decide whether it is ready to ship to production or not. after all, it's THAT developer that's on the hook when his/her app breaks, not the developers contributing to the dependency. some developers like to take risks and run experiments, and there is definitely value to be gained from that approach, but speaking from personal experience, you do NOT want to be in one of the following situations 6 months from now, assuming you are professionally maintaining a beloved app:
- you notice a critical bug in your app, realize it is caused by one of the dependencies that is the foundation of your app, only to find the github issue on the project page describing the issue you are encountering with dozens of responses but no solution. unfortunately, you failed to noticed this critical issue at the time that you decided to integrate it because you didn't or couldn't possibly carefully wade through all 200+ open issues
- you desire a bug fix or feature from the upstream branch of the dependency, only to realize that is accompanied by breaking API changes and there is no clear migration guide and you are stuck having to update your entire codebase to benefit from whatever bug fix or feature you desired

personally, my recommendation is to roll your own FRP primitives like Futures and Signals, which is actually quite easy in Swift. the great thing is you can even find resources from the authors of RAC that can help get you started. I also wouldn't approach FRP as an "all-or-nothing" type of thing, feel free to mix and match with KVO/delegates/blocks/closures/NSNotifications where necessary, appropriate, or convenient. but you are correct in your reasoning that an FRP approach will help you thin your view controllers (e.g. using MVVM).

if you are really desperate to integrate a 3rd-party monolithic framework into the core of your app, there is also [RxSwift](https://github.com/ReactiveX/RxSwift), which has far fewer outstanding issues and plenty of illuminating documentation as well as an excellent set of tutorial playgrounds (no offense intended to the ReactiveCocoa team, who also do a great job with a very difficult task). RxSwift released v2 on January after 4 months (!!) of alpha/beta releases, so it should be pretty good to go at this point.

**Comment by mdiep** [comment] 2016-02-06 23:58
> I wouldn't consider a project with >200 open issues to be production-viable

1. At least 77 of those are labeled questions. We've encouraged people to open issues here to ask for help.
2. A great number of questions are likely not labeled.
3. Another 30 are labeled enhancements
4. A number of the remainder are likely stale
5. Many of them are definitely Objective-C specific.
6. This project is much older than RxSwift, so things have had a longer time to surface.
7. This project is much more complex than something like Alamofire.

You say "200+" as if to suggest that this project is very buggy. There are certainly bugs. But you're painting an inaccurate picture.

**Comment by RuiAAPeres** [comment] 2016-02-07 02:20
@dfischbach I have been using version 4.0 in production quite successfully. Regarding examples, I have been working in a couple of those [here](https://github.com/RuiAAPeres/RACNest) in conjunction with MVVM.

@ILI4S  

> personally, my recommendation is to roll your own FRP primitives like Futures and Signals, which is actually quite easy in Swift.

That's all fine, but you shouldn't undervalue the work/experience of the guys that contribute to it, like @NachoSoto @JaviSoto @neilpa @andymatuschak @jspahrsummers and others. Yes, you can perfectly, roll your own thing, but IMHO I seriously doubt it will have the same quality, or be as battle tested as RAC is. 

>  I also wouldn't approach FRP as an "all-or-nothing" type of thing, feel free to mix and match with KVO/delegates/blocks/closures/NSNotifications where necessary, appropriate, or convenient

That's very much true, it's not "all-or-nothing", but I think you will lose a lot by mixing it with other patterns. I even dare to say that you are completely missing the whole point if you do so. 

> if you are really desperate to integrate a 3rd-party monolithic framework into the core of your app

Compared to RxSwift, RAC 4.0 is a feather (looking only at the [Swift work](https://github.com/ReactiveCocoa/ReactiveCocoa/tree/master/ReactiveCocoa/Swift) and discarding the Objc baggage, which you don't need to use). This ofc has its pros/cons. RxSwift [UI catalogue](https://github.com/ReactiveX/RxSwift/tree/master/RxCocoa) is **pretty impressive** and something that we are now seeing with @neilpa 's [Rex] (https://github.com/neilpa/Rex) at a smaller scale.

> RxSwift released v2 on January after 4 months (!!) of alpha/beta releases, so it should be pretty good to go at this point. 

Although that might be true, and tbh @kzaher has been doing an **excellent job**, RxSwift is pretty much a one man show, which ofc has its cons:

<img width="992" alt="screen shot 2016-02-07 at 02 14 35" src="https://cloud.githubusercontent.com/assets/949286/12870516/7cacb43c-cd40-11e5-82a9-53b5765e5221.png">

So be aware of this fact, when choosing a dependency.

**Comment by ILI4S** [comment] 2016-02-07 20:56
I agree with everything @mdiep and @RuiAAPeres contributed and am happy I was able to encourage further discussion. I really appreciate your responses and the time that everyone in the community puts into this project.

My intention was not to portray the codebase as buggy due to the number of issues, only to draw attention to the fact its difficult to gain an overview of the status of the project with so many open issues. While I am sure that there are advantages to having a question label (for example, this question we are responding to right now), other projects encourage questions to be asked on StackOverflow with a tag e.g. `RAC` or `ReactiveCocoa`

I only wish that some of the information and resources @RuiAAPeres shared would be elaborated upon in more detail and more accessible to help developers such as @ceeK and myself make more informed decisions. 

Thanks, guys 👍

**Comment by RuiAAPeres** [comment] 2016-04-14 15:57
@ILI4S I started working on the ReactiveCocoa's playground ( #2795 ), which will help new comers have a better understanding of how to use ReactiveCocoa. I am also proposing including Rex in this organization ( #2790 ). So in a nutshell there is an on-going effort to clean up and make it more "user friendly" for everyone. 

 On the meantime, if we were able to answer yours and @ceeK questions, please close the issue.

**Closed** 2016-04-14 23:38 UTC
Labels: question
