### ISSUE TITLE
Xcode 7.3 error on __weak usage

### ISSUE THREAD

**Issue by KyleLeneau** [ReactiveCocoa/ReactiveCocoa#2768] opened 2016-03-23 06:55 UTC
It looks like something might have changed with Xcode 7.3 and the use of `__weak` annotations for the compiler. I seem to be getting a compile error that stems back to this commit: https://github.com/ReactiveCocoa/ReactiveCocoa/commit/2f48434980cbd357142b7eaa3a3ecad5642d1b77

The error I am getting is: `/ReactiveCocoa/ReactiveCocoa/Objective-C/NSObject+RACPropertySubscribing.h:72:67: Cannot create __weak reference in file using manual reference counting` I am also getting the same with `KVOChannel.h`.

The question here is, are these annotations still needed in master (4.0) now that Xcode 7.3 is available. When I comment them out everything work great.

**Comment by DeveloperZhangJi** [comment] 2016-03-23 07:20
Did you fix that?

**Comment by KyleLeneau** [comment] 2016-03-23 07:26
No, here is some more information on the topic though: https://forums.developer.apple.com/thread/38934

**Comment by gcox** [comment] 2016-03-23 19:11
Duplicate of #2699 & #2761 

This appears to be the easiest fix: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2761#issuecomment-200171258

**Comment by mdiep** [comment] 2016-03-26 17:56
Closing this because there doesn't seem like there's any work to be done in RAC.

tl;dr: In Xcode 7.3, `__weak` causes errors in files compiled as `-fno-objc-arc`. Since RAC uses `__weak`, you cannot use it in those files without setting the `Weak References in Manual Retain Release` setting to `YES`. If you're using a `.pch` that imports RAC, you're more likely to see this error.

**Closed by mdiep** 2016-03-26 17:56 UTC
