### ISSUE TITLE
Bi-directional MutableProperty binding

### ISSUE THREAD

**Issue by gavrix** [ReactiveCocoa/ReactiveCocoa#1911] opened 2015-04-17 23:14 UTC
Currently, `MutableProperty` implements `Signal` (via `producer` property) and `SinkType` effectively allowing cross bind two mutable properties to each other. Within current implementation that leads to a loop.

In RAC2 we had `RACChannel`concept and ability to bind two KVO observings through `RACChannelTo` macro. 

Would it make more sense to make `MutableProperty` act same way as RACChannelTerminal? Meaning, whenever value came from a signal bound to this property do not pass it into own producer, and only pass those values set directly through calling 
```
property.value = <value>
```

BTW, within current implementation, even though `MutableProperty` conforms to `SinkType` (has `put` method) values coming from signal set to the property thorough it's `value` property. ([here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v3.0-beta.1/ReactiveCocoa/Swift/Property.swift#L180-L184))

**Comment by gavrix** [comment] 2015-04-20 00:03
After having a second though I tried modelling the use case and ended up with `PropertyTermianl` #1915  which sort of fixed my problem of mutual property bindings

**Comment by jspahrsummers** [comment] 2015-04-21 00:12
Thanks for the issue and the pull request! :sparkles:

The reason channels and terminals haven't been ported to RAC 2.x is because **two-way bindings are hard**, and I don't think we've gotten it right yet. I'd even go further and argue that two-way bindings are _usually_ a smell, and should be reformulated to explicitly give precedence to one side or the other.

Although I am interested in revisiting two-way bindings at some point in the future, I don't think we should include anything in the first release of RAC 3.0—because then we're required to support it for all future updates in the 3.x cycle.

/cc @Coneko @andymatuschak who also care a lot about this problem

**Comment by gavrix** [comment] 2015-04-21 00:57
Ok I got that.

Just for the note, a couple of words about reasoning behind that mutual properties binding.
I was looking first time how I can replace `RAC`/`RACObserve` in my particular uses, for example `UIButton`'s `enabled` property. I have to use `DynamicProperty` but this property is of type `AnyObject?` and ideally I would implement that property in ViewModel as `Bool`. So I tried to hide that `AnyObject?` property with something which could bind to `Bool`-parameterized property.

ended up with this:

```swift
class PropertiesContainer<P1 : MutablePropertyType, P2 : MutablePropertyType> {
    let proxyProperty : P1
    let originalProperty : P2
    init (proxy : P1, original : P2) {
        self.proxyProperty = proxy
        self.originalProperty = original;
    }
}

extension UIControl {


    private struct AssociatedKeys {
        static var EnabledProperty = 0
    }

    
    public var enabledProperty : MutableProperty<Bool> {
        get {
            typealias EnabledPropertyProxyCotnainerType = PropertiesContainer<PropertyTerminal<MutableProperty<Bool>>, PropertyTerminal<DynamicProperty>>
            var propertiesPair : EnabledPropertyProxyCotnainerType?

            propertiesPair = objc_getAssociatedObject(self, &AssociatedKeys.EnabledProperty) as? EnabledPropertyProxyCotnainerType
            if propertiesPair == nil {
                let proxyProeprty = PropertyTerminal(property: MutableProperty(self.enabled))
                let originProperty = PropertyTerminal(property: DynamicProperty(object: self, keyPath: "enabled"));

                originProperty <~ proxyProeprty.producer |> map { $0 as AnyObject }
                proxyProeprty <~ originProperty.producer |> filter {$0 is Bool } |> map { $0 as! Bool }

                propertiesPair = PropertiesContainer(proxy: proxyProeprty, original: originProperty)
                objc_setAssociatedObject(self, &AssociatedKeys.EnabledProperty, propertiesPair, UInt(OBJC_ASSOCIATION_RETAIN))
            }

            return propertiesPair!.proxyProperty.property
        }
    }

}

``` 

So that was my uses case of mutual binding to provide type cast for Dynamic properties.

What's your thoughts on this problem? I mean typecasting `DynamicProperty` ?

**Comment by jspahrsummers** [comment] 2015-05-03 23:20
I would avoid `DynamicProperty` (as suggested in its type documentation) for UI bindings, and simply use `observe(next:)` or `start(next:)` to perform a direct assignment instead. That should avoid most of the complexity, I think.

**Comment by jspahrsummers** [comment] 2015-05-03 23:21
With regard the original gist of this issue, I started [an add-on library](https://github.com/ReactiveCocoa/EditableProperty) for multi-way bindings in RAC 3. It's still very premature, though, and I can't recommend it for real world use yet.

**Comment by kevin-hirsch** [comment] 2015-10-05 16:14
Hey @jspahrsummers, is there any updates on the multi-way bindings with RAC 3? I would be very interested to have the two-way binding. Thanks!

**Comment by jspahrsummers** [comment] 2015-10-05 16:28
There are no updates. That library isn't mature enough to include in RAC proper.

**Comment by andymatuschak** [comment] 2015-10-05 16:30
++

Two-way binding is a significantly more open problem than the rest of RAC; I think it makes much more sense to explore implementations in auxiliary libraries.

**Comment by kevin-hirsch** [comment] 2015-10-05 16:33
Okay. So nothing planned at this time?

**Comment by jspahrsummers** [comment] 2015-10-05 16:38
Plans for various versions of RAC are captured in milestones: https://github.com/ReactiveCocoa/ReactiveCocoa/milestones

Since this isn't milestoned, it probably won't be addressed in the near future.

**Comment by neilpa** [comment] 2015-10-17 10:51
I'll add that I don't see any future where we have a good answer for bi-directional bindings w/RAC. `EditableProperty` is a cool idea that I wanted to work but found difficult to integrate to a project. It could be improved, but I have my doubts it'll every be simple enough for most people to just pickup and use. RAC is already a lot to grok when coming from a stateful world.

IMO, the problem lies with how Cocoa (and most UI frameworks) are fundamentally designed. Specifically text input fields where 2-way binding is most often desired. The problem is input is super hard. It involves language, keyboard, cursor/focus, selection, UI, etc. For that reason frameworks take on the burden wholesale coupling all the inputs and outputs.

**Comment by RuiAAPeres** [comment] 2016-04-22 00:09
Closing due to inactivity.

**Closed by RuiAAPeres** 2016-04-22 00:09 UTC
Labels: enhancement, question
