### ISSUE TITLE
Flatten works differently 4.1.0 -> 4.2.1

### ISSUE THREAD

**Issue by gbrhaz** [ReactiveCocoa/ReactiveCocoa#3151] opened 2016-08-25 20:57 UTC
I've just updated RAC from 4.1.0 to 4.2.1 and I had some code like:

`mutableProperty <~ SignalProducer(values: [amount.producer, discount.producer, total.producer]).flatten(.Latest).map { _ in /* bla bla bla */ }`

In 4.1.0 this would load fine when those three producers changed values; now they don't. What's changed and what's the new solution?

**Comment by ikesyo** [comment] 2016-08-25 22:40
That is a duplicate of #3037 and fixed in 4.2.2. Can you please update to the version?

**Closed** 2016-08-25 22:42 UTC
Labels: duplicate
