### ISSUE TITLE
swift2 branch fails to build through Carthage on Xcode 7 beta 6

### ISSUE THREAD

**Issue by erikjalevik** [ReactiveCocoa/ReactiveCocoa#2319] opened 2015-09-07 11:26 UTC
I am trying to build RAC through Carthage with the following configuration:

RAC branch "swift2" @ 5e75726bf232b76b17169b3d9c9c64d1fd6bffbe
Xcode 7 beta 6
OSX Yosemite 10.10.5

However, it always fails with an error of:

> The following build commands failed:
>	Check dependencies
> (1 failure)
> CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.0'
> A shell task failed with exit code 65:
> ** BUILD FAILED **

Looking at the log, this happens straight after the line:

> Build settings from command line:
>    SDKROOT = iphoneos9.0
>
> === BUILD TARGET Result-watchOS OF PROJECT Result WITH CONFIGURATION Release ===

We have now seen this problem on two different machines. Any ideas?

**Comment by Fab1n** [comment] 2015-09-07 14:56
same here for us, but we get 
```
carthage update
*** Fetching ReactiveCocoa
*** Fetching Result
Parse error: expected submodule commit SHA in ls-tree output: 
```

**Comment by wynch** [comment] 2015-09-07 15:49
I just built ReactiveCocoa on branch Swift2 with no problem... 

Make sure you have the right xcodebuild selected : XCode > Preferences > Locations > Command-line tools, make sure XCode 7.0 beta is selected (and not XCode 6)

**Comment by neilpa** [comment] 2015-09-07 19:52
> Parse error: expected submodule commit SHA in ls-tree output: 

This usually means something is broken with git submodules in your project. Make sure that `.gitmodules` and `.git/config` look right. Otherwise you may want to try deleting the carthage git cache at `~/Library/Caches/org.carthage.CarthageKit/dependencies`.

**Comment by laptobbe** [comment] 2015-09-07 22:05
I am experiencing the same issue @erikjalevik, did you find a solution?

**Comment by Fab1n** [comment] 2015-09-07 22:10
OK `carthage build --platform WatchOS --verbose` works. WatchOS is making issues

**Comment by Fab1n** [comment] 2015-09-07 22:11
Also, a Cartfile should reside within the same folder as `.git`

**Comment by laptobbe** [comment] 2015-09-07 22:15
I don't seem to have a --platform WatchOS, it's saying:
````
Invalid value for '--platform': WatchOS
````
I might be running an old version of Carthage but brew says its the latest one.

**Comment by rpowelll** [comment] 2015-09-07 23:23
I managed to fix my problems with watchOS builds by going into the device organiser in Xcode (⇧⌘2) and making sure I had a simulator with a paired watch. If there's not one there, just click the + icon at the bottom of the source list and add one.

**Comment by Fab1n** [comment] 2015-09-08 07:02
@rpowelll good point. I have to try it.

@laptobbe you have to use carthage version 0.8.0

**Comment by laptobbe** [comment] 2015-09-08 07:08
@Fab1n Thanks, forgot to run.
````
brew update
````
It now works with carthage 0.8.0 installed. Note you need to switch to Xcode 6 on the command line to update carthage via brew. And then back to Xcode 7 to install ReactiveCocoa via carthage.

**Comment by erikjalevik** [comment] 2015-09-08 07:45
OK, after upgrading Carthage to 0.8, I can now build the whole shebang (I think) by executing:

`carthage build --platform WatchOS`
`carthage build --platform iOS`
`carthage build --platform Mac`

However, `carthage build` on its own still errors out.

**Comment by rpowelll** [comment] 2015-09-08 23:21
Are you seeing the same error as before or a different one?

**Comment by erikjalevik** [comment] 2015-09-09 09:32
Exactly the same one. And on my colleague's machine, we get the error even when building the platforms separately.

**Comment by Fab1n** [comment] 2015-09-09 09:34
Did you close Xcode on your college's machine? We experienced a difference between Xcode being open or closed

**Comment by adly-holler** [comment] 2015-09-09 23:45
I'm in a similar situation with @erikjalevik I've got two machines, both on latest Yosemite, both on Xcode 7 GM Carthage 0.8.0 and on one, ReactiveCocoa-iOS builds fine but on the other, it errors out with this code signing issue

**Comment by iv-mexx** [comment] 2015-09-10 10:25
> Did you close Xcode on your college's machine? We experienced a difference between Xcode being open or closed

I had the same code signing issue. Closing Xcode has actually fixed the problem for me, running `carthage build --platform iOS` works now when Xcode is closed... :laughing:

**Comment by chrene** [comment] 2015-09-10 22:59
Closing Xcode also fixed it for me. Weird though.

**Comment by neilpa** [comment] 2015-09-10 23:56
> Closing Xcode also fixed it for me. Weird though.

That explains why I couldn't find the actual repo since I wasn't paying attention to that as I tweaked the `project.pbxproj` trying to figure this out.

**Comment by calebd** [comment] 2015-09-12 00:12
Closing Xcode appears to work _sometimes_. Now I can't get it to build at all and can't figure out how to make it work again.

**Comment by ninokierulf** [comment] 2015-09-17 07:33
Not able to build ReactiveCocoa swift2 branch.
I created a very fresh project with no implementation and no other dependencies.

Carthage file content:
```
github "ReactiveCocoa/ReactiveCocoa" "swift2"
```

when I run `carthage update` OR `carthage build --no-skip-current`
```
Failed to discover shared schemes in project ReactiveCocoa.xcworkspace—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/ReactiveCocoa/ReactiveCocoa/issues/new
```

I tried `xcodebuild -scheme SCHEME -project PROJECT build` and was able to build sucessfully meaning it's not the project file.

Xcode 7.1 beta (7B60), 
command line tools: Xcode7.1(7B60)
cartage version: 0.8.0

PS: I also tried while xCode is closed

**Comment by mdiep** [comment] 2015-09-23 18:13
I haven't been able to reproduce this with the Xcode 7 GM. :confused:

**Comment by ikesyo** [comment] 2016-04-23 12:20
This should not be a problem anymore, since we have stable `master` branch that is compatible with Swift 2.2 / Xcode 7.3. Closing.

**Closed by ikesyo** 2016-04-23 12:20 UTC
