### ISSUE TITLE
New release for Xcode 11 and Swift 5.1

### ISSUE THREAD

**Issue by hieuhuynh0412** [ReactiveCocoa/ReactiveCocoa#3685] opened 2019-09-10 04:06 UTC
Hi there,
I noticed that ReactiveSwift 6.1 supported Xcode 11 and Swift 5.1 already
So I would like to know when the next release ReactiveCocoa support for Xcode 11 and Swift 5.1?

**Comment by ikesyo** [comment] 2019-09-10 14:53
Duplicate of #3684.

**Closed by ikesyo** 2019-09-10 14:53 UTC
