### ISSUE TITLE
"Invalid pointer dequeued from free list" crash when using `skipRepeats` 

### ISSUE THREAD

**Issue by kaybutter** [ReactiveCocoa/ReactiveCocoa#1890] opened 2015-04-12 17:03 UTC
I have been experiencing weird crashes since updating to Swift 1.2. They seem to be connected to `skipRepeats` or its call to `combinePrevious`. 

This simple example will reproduce the crash for me:

``` Swift
SignalProducer<String, NoError>(values: ["a", "b", "c", "a", "a", "c"])
  |> skipRepeats
  |> reduce("", +)
  |> start(next: { string in
    NSLog("\(string)")
  })
```

It crashes with a `SIGABRT` in `combinePrevious` that is used by `skipRepeats` and prints the following:

```
malloc: *** error for object 0x610000261f00: Invalid pointer dequeued from free list
*** set a breakpoint in malloc_error_break to debug
```

I have set up an example project that demonstrates the issue:
https://github.com/kaybutter/rac-crash

**Comment by codeflows** [comment] 2015-04-12 18:00
Tried the example project and it's crashing for me as well: https://gist.github.com/codeflows/c11a661251d0b86074fb

**Comment by NachoSoto** [comment] 2015-04-12 19:19
I just hit this as well in my own app :/ I'm using `skipRepeats` in several places, but only one of them reproduced this issue.

**Comment by jspahrsummers** [comment] 2015-04-13 05:00
As with https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1888#issuecomment-92211972, any kind of memory corruption sounds like a Swift toolchain issue.

We should try finding a workaround, but I would suggest filing a radar so the underlying problem gets fixed.

**Comment by JaviSoto** [comment] 2015-04-18 22:58
I'm getting a different crash here now after https://github.com/ReactiveCocoa/ReactiveCocoa/pull/1902 :-/

![screen shot 2015-04-18 at 3 57 48 pm](https://cloud.githubusercontent.com/assets/666807/7217512/b6d953ee-e5e3-11e4-8ca9-49635db9e771.png)

**Comment by JaviSoto** [comment] 2015-04-19 20:21
@NachoSoto gave me a great idea for a workaround. This doesn't crash:

```swift
public func skipRepeatsWorkAround<T, E>(isRepeat: (T, T) -> Bool)(signal: Signal<T, E>) -> Signal<T, E> {
	return signal
		|> map { Box($0) }
		|> skipRepeats { isRepeat($0.unbox, $1.unbox) }
		|> map { $0.unbox }
}
```

**Comment by NachoSoto** [comment] 2015-04-19 20:38
![sad](https://cloud.githubusercontent.com/assets/685609/7221277/36e4c52c-e699-11e4-8e38-3ecac3d8422c.gif)

**Comment by kommen** [comment] 2015-04-20 20:38
I just ran into that. Filed http://openradar.appspot.com/20621873 if anybody wants to dupe.

**Comment by shrutic** [comment] 2016-09-08 18:46
Do we know if the radar has been fixed. AKA Is the radar in the public domain updated when the radar is updated privately?

**Comment by kommen** [comment] 2016-09-12 19:36
@shrutic the crash was fixed in Xcode 6.4 (6E35b) and the radar was closed back then.

**Comment by SummerAfter** [comment] 2016-10-28 07:08
how can i solve it?

**Comment by NachoSoto** [comment] 2017-02-06 03:49
I'm seeing this again in Swift 3 (on https://github.com/NachoSoto/AsyncImageView) 😢

**Comment by liscio** [comment] 2017-02-06 13:19
@NachoSoto If it's consistently crashing, does it also consistently crash with either of the thread or memory sanitizer enabled? That'd help nail down the cause if you can catch one that way.

**Comment by HPRaval** [comment] 2017-06-28 10:12
i have similar problem...please help me...

**Comment by RuiAAPeres** [comment] 2021-07-22 08:13
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄

**Closed by RuiAAPeres** 2021-07-22 08:13 UTC
Labels: bug, help wanted
