### ISSUE TITLE
combineLatest not working with signal for array changes

### ISSUE THREAD

**Issue by ChrisXu1221** [ReactiveCocoa/ReactiveCocoa#2437] opened 2015-10-01 09:08 UTC
I know it doesn't work with monitoring the collection change of an set/array. Therefore every time when I added an object to the set/array, I recreate the set/array object and assign it to the property in order to be observed.

Which works fine with the following code.
```
RACSignal *arraySignal = [RACObserve(self, array) subscribeNext:^(id x) {
// do something
 }];
```

But it won't work with this.
```
RACSignal *arraySignal = RACObserve(self, array);

RACSignal *check = [RACSignal combineLatest:@[ arraySignal ]
                                         reduce:^(NSMutableSet *array) {
                                             // do something
                                             return @(array != nil);
                                         }];

UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
    RAC(button,enabled) = check;
```

Any thought?

**Comment by ikesyo** [comment] 2016-04-25 18:26
I couldn't reproduce the issue. That worked for me. Closing.

> `UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];`

Maybe the button instance will be deallocated immediately in the example.

**Closed by ikesyo** 2016-04-25 18:26 UTC
Labels: legacy-objc, question
