### ISSUE TITLE
RAC 3: EXC_BAD_ACCESS crash running on test device (works in simulator)

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2056] opened 2015-05-29 22:08 UTC
This line:
`buttonAction = CocoaAction(viewModel.loginAction, input:"touchdown")`

Causes the following error when running on the device. The app runs fine from simulator. The only thing of note is that I am embedding RAC, Result, and Box frameworks via the Embedded Binaries option to make sure this doesn't happen: http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta

```Swift
* thread #1: tid = 0x9d678, 0x0000000000000000, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
    frame #1: 0x0000000100b96588 ReactiveCocoa`partial apply forwarder for Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) with unmangled suffix "790" [inlined] Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) + 20 at Signal.swift:0
    frame #2: 0x0000000100b96574 ReactiveCocoa`partial apply forwarder for Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) with unmangled suffix "790" + 52 at Signal.swift:0
    frame #3: 0x0000000100b967a0 ReactiveCocoa`ReactiveCocoa.Signal.(init <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.Signal<A, B>.Type) -> ((Swift.SinkOf<ReactiveCocoa.Event<A, B>>) -> Swift.Optional<ReactiveCocoa.Disposable>) -> ReactiveCocoa.Signal<A, B>).(closure #1) [inlined] Swift.SinkOf.put <A>(Swift.SinkOf<A>)(A) -> () + 8 at Signal.swift:0
    frame #4: 0x0000000100b96798 ReactiveCocoa`ReactiveCocoa.Signal.(event=ReactiveCocoa.Event<T, E> at x19, self=0x000000017404bb20, generatorDisposable=<unavailable>) -> ((Swift.SinkOf<ReactiveCocoa.Event<A, B>>) -> Swift.Optional<ReactiveCocoa.Disposable>) -> ReactiveCocoa.Signal<A, B>).(closure #1) + 504 at Signal.swift:44
    frame #5: 0x0000000100bbaab0 ReactiveCocoa`ReactiveCocoa.SignalProducer.(startWithSignal <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.SignalProducer<A, B>) -> ((ReactiveCocoa.Signal<A, B>, ReactiveCocoa.Disposable) -> ()) -> ()).(closure #2) [inlined] Swift.SinkOf.put <A>(Swift.SinkOf<A>)(A) -> () + 8 at SignalProducer.swift:0
    frame #6: 0x0000000100bbaaa8 ReactiveCocoa`ReactiveCocoa.SignalProducer.(event=<unavailable>, observer=<unavailable>, compositeDisposable=<unavailable>) -> ((ReactiveCocoa.Signal<A, B>, ReactiveCocoa.Disposable) -> ()) -> ()).(closure #2) + 116 at SignalProducer.swift:202
    frame #7: 0x0000000100b96588 ReactiveCocoa`partial apply forwarder for Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) with unmangled suffix "790" [inlined] Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) + 20 at Signal.swift:0
    frame #8: 0x0000000100b96574 ReactiveCocoa`partial apply forwarder for Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) with unmangled suffix "790" + 52 at Signal.swift:0
    frame #9: 0x0000000100b967a0 ReactiveCocoa`ReactiveCocoa.Signal.(init <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.Signal<A, B>.Type) -> ((Swift.SinkOf<ReactiveCocoa.Event<A, B>>) -> Swift.Optional<ReactiveCocoa.Disposable>) -> ReactiveCocoa.Signal<A, B>).(closure #1) [inlined] Swift.SinkOf.put <A>(Swift.SinkOf<A>)(A) -> () + 8 at Signal.swift:0
    frame #10: 0x0000000100b96798 ReactiveCocoa`ReactiveCocoa.Signal.(event=ReactiveCocoa.Event<T, E> at x19, self=0x000000017404bd00, generatorDisposable=<unavailable>) -> ((Swift.SinkOf<ReactiveCocoa.Event<A, B>>) -> Swift.Optional<ReactiveCocoa.Disposable>) -> ReactiveCocoa.Signal<A, B>).(closure #1) + 504 at Signal.swift:44
    frame #11: 0x0000000100b95be4 ReactiveCocoa`partial apply forwarder for ReactiveCocoa.(observeOn <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.SchedulerType) -> (ReactiveCocoa.Signal<A, B>) -> ReactiveCocoa.Signal<A, B>).(closure #1).(closure #1).(closure #1).(closure #1) [inlined] Swift.SinkOf.put <A>(Swift.SinkOf<A>)(A) -> () + 104 at Signal.swift:0
    frame #12: 0x0000000100b95bdc ReactiveCocoa`partial apply forwarder for ReactiveCocoa.(observeOn <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.SchedulerType) -> (ReactiveCocoa.Signal<A, B>) -> ReactiveCocoa.Signal<A, B>).(closure #1).(closure #1).(closure #1).(closure #1) + 8 at Signal.swift:241
    frame #13: 0x0000000100b95bd4 ReactiveCocoa`partial apply forwarder for ReactiveCocoa.(observeOn <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.SchedulerType) -> (ReactiveCocoa.Signal<A, B>) -> ReactiveCocoa.Signal<A, B>).(closure #1).(closure #1).(closure #1).(closure #1) + 88 at Signal.swift:0
    frame #14: 0x0000000100bd3978 ReactiveCocoa`ReactiveCocoa.UIScheduler.schedule (ReactiveCocoa.UIScheduler)(() -> ()) -> Swift.Optional<ReactiveCocoa.Disposable> [inlined] ReactiveCocoa.UIScheduler.(schedule (ReactiveCocoa.UIScheduler) -> (() -> ()) -> Swift.Optional<ReactiveCocoa.Disposable>).(closure #1) + 256 at Scheduler.swift:67
    frame #15: 0x0000000100bd395c ReactiveCocoa`ReactiveCocoa.UIScheduler.schedule ($return_value=<invalid> (0x30), action=<unavailable>, self=<unavailable>)(() -> ()) -> Swift.Optional<ReactiveCocoa.Disposable> + 228 at Scheduler.swift:78
    frame #16: 0x0000000100b97c1c ReactiveCocoa`ReactiveCocoa.(event=ReactiveCocoa.Event<T, E> at x19, scheduler=<unavailable>, observer=<unavailable>) -> (ReactiveCocoa.Signal<A, B>) -> ReactiveCocoa.Signal<A, B>).(closure #1).(closure #1).(closure #1) + 212 at Signal.swift:242
    frame #17: 0x0000000100b96588 ReactiveCocoa`partial apply forwarder for Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) with unmangled suffix "790" [inlined] Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) + 20 at Signal.swift:0
    frame #18: 0x0000000100b96574 ReactiveCocoa`partial apply forwarder for Swift.SinkOf.(init <A>(Swift.SinkOf<A>.Type) -> <B : Swift.SinkType>(B) -> Swift.SinkOf<A>).(closure #1) with unmangled suffix "790" + 52 at Signal.swift:0
    frame #19: 0x0000000100b967a0 ReactiveCocoa`ReactiveCocoa.Signal.(init <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.Signal<A, B>.Type) -> ((Swift.SinkOf<ReactiveCocoa.Event<A, B>>) -> Swift.Optional<ReactiveCocoa.Disposable>) -> ReactiveCocoa.Signal<A, B>).(closure #1) [inlined] Swift.SinkOf.put <A>(Swift.SinkOf<A>)(A) -> () + 8 at Signal.swift:0
    frame #20: 0x0000000100b96798 ReactiveCocoa`ReactiveCocoa.Signal.(event=ReactiveCocoa.Event<T, E> at x19, self=0x000000017404bbb0, generatorDisposable=<unavailable>) -> ((Swift.SinkOf<ReactiveCocoa.Event<A, B>>) -> Swift.Optional<ReactiveCocoa.Disposable>) -> ReactiveCocoa.Signal<A, B>).(closure #1) + 504 at Signal.swift:44
    frame #21: 0x0000000100bbaab0 ReactiveCocoa`ReactiveCocoa.SignalProducer.(startWithSignal <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.SignalProducer<A, B>) -> ((ReactiveCocoa.Signal<A, B>, ReactiveCocoa.Disposable) -> ()) -> ()).(closure #2) [inlined] Swift.SinkOf.put <A>(Swift.SinkOf<A>)(A) -> () + 8 at SignalProducer.swift:0
    frame #22: 0x0000000100bbaaa8 ReactiveCocoa`ReactiveCocoa.SignalProducer.(event=<unavailable>, observer=<unavailable>, compositeDisposable=<unavailable>) -> ((ReactiveCocoa.Signal<A, B>, ReactiveCocoa.Disposable) -> ()) -> ()).(closure #2) + 116 at SignalProducer.swift:202
    frame #23: 0x0000000100bba0b4 ReactiveCocoa`static ReactiveCocoa.SignalProducer.(buffer <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.SignalProducer<A, B>.Type) -> (Swift.Int) -> (ReactiveCocoa.SignalProducer<A, B>, Swift.SinkOf<ReactiveCocoa.Event<A, B>>)).(closure #1) [inlined] Swift.SinkOf.put <A>(Swift.SinkOf<A>)(A) -> () + 524 at SignalProducer.swift:0
    frame #24: 0x0000000100bba0ac ReactiveCocoa`static ReactiveCocoa.SignalProducer.(observer=<unavailable>, disposable=<unavailable>, lock=<unavailable>, events=<unavailable>, terminationEvent=<unavailable>, observers=Swift.Optional<ReactiveCocoa.Bag<Swift.SinkOf<ReactiveCocoa.Event<T, E>>>> at 0x000000017004fd90) -> (Swift.Int) -> (ReactiveCocoa.SignalProducer<A, B>, Swift.SinkOf<ReactiveCocoa.Event<A, B>>)).(closure #1) + 516 at SignalProducer.swift:120
    frame #25: 0x0000000100bacd34 ReactiveCocoa`partial apply forwarder for static ReactiveCocoa.SignalProducer.(buffer <A, B : ReactiveCocoa.ErrorType>(ReactiveCocoa.SignalProducer<A, B>.Type) -> (Swift.Int) -> (ReactiveCocoa.SignalProducer<A, B>, Swift.SinkOf<ReactiveCocoa.Event<A, B>>)).(closure #1) + 164 at SignalProducer.swift:0
    frame #26: 0x0000000100bad1fc ReactiveCocoa`ReactiveCocoa.SignalProducer.startWithSignal <A, B : ReactiveCocoa.ErrorType>(setUp=<unavailable>, self=<unavailable>)((ReactiveCocoa.Signal<A, B>, ReactiveCocoa.Disposable) -> ()) -> () + 484 at SignalProducer.swift:211
    frame #27: 0x0000000100bad1fc ReactiveCocoa`ReactiveCocoa.SignalProducer.startWithSignal <A, B : ReactiveCocoa.ErrorType>(setUp=<unavailable>, self=<unavailable>)((ReactiveCocoa.Signal<A, B>, ReactiveCocoa.Disposable) -> ()) -> () + 484 at SignalProducer.swift:211
    frame #28: 0x0000000100bad4c4 ReactiveCocoa`ReactiveCocoa.SignalProducer.start <A, B : ReactiveCocoa.ErrorType>(self=ReactiveCocoa.SignalProducer<T, E> at x2)<C : Swift.SinkType>(C) -> ReactiveCocoa.Disposable + 180 at SignalProducer.swift:226
    frame #29: 0x0000000100bde4f8 ReactiveCocoa`ReactiveCocoa.CocoaAction.init (action=<unavailable>, inputTransform=<unavailable>, self=<unavailable>)<A, B, C : ReactiveCocoa.ErrorType>(ReactiveCocoa.Action<A, B, C>, (Swift.Optional<Swift.AnyObject>) -> A) -> ReactiveCocoa.CocoaAction + 1024 at Action.swift:165
    frame #30: 0x0000000100bde9fc ReactiveCocoa`ReactiveCocoa.CocoaAction.init (action=(null) at x20, self=<unavailable>)<A, B, C : ReactiveCocoa.ErrorType>(ReactiveCocoa.Action<A, B, C>, input : A) -> ReactiveCocoa.CocoaAction + 244 at Action.swift:187
  * frame #31: 0x000000010046c3d0 POV.psychiatry`POV.LoginViewController.(self=0x0000000144d14c10) (POV.LoginViewController)() -> () + 1812 at LoginViewController.swift:79
    frame #32: 0x000000010046b140 `POV.LoginViewController.viewDidLoad (self=0x0000000144d14c10)() -> () + 180 at LoginViewController.swift:49
    frame #33: 0x000000010046b17c POV.psychiatry`@objc POV.LoginViewController.viewDidLoad (POV.LoginViewController)() -> () + 40 at LoginViewController.swift:0
```

**Comment by MichaelMcGuire** [comment] 2015-05-29 22:25
Duplicate of #2000? Which version are you using?  Supposed to have been fixed in latest.

**Comment by nomothetis** [comment] 2015-05-29 22:31
For what it's worth, the pattern that caused #2000 also causes breakage in RAC-based frameworks. We might want to document that in the API. I can create a PR if needed.

**Comment by RuiAAPeres** [comment] 2016-04-22 00:11
Closing due to inactivity.

**Closed by RuiAAPeres** 2016-04-22 00:11 UTC
